export const AUTH_SERVICE_ERROR_CODE = {
  BAD_LOGIN_TEXT: 'INVALID_CREDENTIALS',
  USER_REGISTRED: 'ACCOUNT_TAKEN',
  UKNOWN: 'SERVER_ERROR',
  NOT_LOGGED: 'INVALID_SESSION_TOKEN',
  EMAIL_NOT_CHECKED: 'EMAIL_NOT_CHECKED',
  EMAIL_WAS_ALREADY_CHECKED: 'EMAIL_WAS_ALREADY_CHECKED',
  INVALID_USER: 'INVALID_USER',
  PASSWORD_NOT_MATCHING: 'PASSWORD_NOT_MATCHING',
  USERNAME_NOT_REGISTRED: 'USERNAME_NOT_REGISTRED',
};
